# Generated by Django 4.1.8 on 2023-04-21 21:25

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.CharField(default=django.utils.crypto.get_random_string, max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
