# Generated by Django 4.1.8 on 2023-04-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_shortlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
