# Generated by Django 4.1.8 on 2023-04-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0003_delete_account_delete_shortlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cluster', models.CharField(max_length=30)),
                ('nivel_governamental', models.IntegerField()),
                ('nome_provedor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inep', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('unidade_federacao', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=50)),
                ('categoria_administrativa', models.IntegerField()),
                ('dependencia_administrativa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_ip', models.CharField(max_length=15)),
                ('node_port', models.IntegerField()),
                ('infraestrutura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='escolas.infraestrutura')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tipo', models.IntegerField(unique=True)),
                ('infraestrutura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato', to='escolas.infraestrutura')),
                ('unidade_escolar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to='escolas.unidadeescolar')),
            ],
        ),
    ]
